<a href="https://colab.research.google.com/github/igors96/RFRegressor_Brazilian_Cities/blob/main/rfregressor_brazilian_cities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 81)
cidades = pd.read_csv('/content/BRAZIL_CITIES.csv', sep = ';', decimal = ',')

In [2]:
cidades.head()

,CITY,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,IBGE_1,IBGE_1-4,IBGE_5-9,IBGE_10-14,IBGE_15-59,IBGE_60+,IBGE_PLANTED_AREA,IBGE_CROP_PRODUCTION_$,IDHM Ranking 2010,IDHM,IDHM_Renda,IDHM_Longevidade,IDHM_Educacao,LONG,LAT,ALT,PAY_TV,FIXED_PHONES,AREA,REGIAO_TUR,CATEGORIA_TUR,ESTIMATED_POP,RURAL_URBAN,GVA_AGROPEC,GVA_INDUSTRY,GVA_SERVICES,GVA_PUBLIC,GVA_TOTAL,TAXES,GDP,POP_GDP,GDP_CAPITA,GVA_MAIN,MUN_EXPENDIT,COMP_TOT,COMP_A,COMP_B,COMP_C,COMP_D,COMP_E,COMP_F,COMP_G,COMP_H,COMP_I,COMP_J,COMP_K,COMP_L,COMP_M,COMP_N,COMP_O,COMP_P,COMP_Q,COMP_R,COMP_S,COMP_T,COMP_U,HOTELS,BEDS,Pr_Agencies,Pu_Agencies,Pr_Bank,Pu_Bank,Pr_Assets,Pu_Assets,Cars,Motorcycles,Wheeled_tractor,UBER,MAC,WAL-MART,POST_OFFICES
0,Abadia De Goiás,GO,0,6876.0,6876.0,0.0,2137.0,1546.0,591.0,5300.0,69.0,318.0,438.0,517.0,3542.0,416.0,319.0,1843.0,1689.0,0.708,0.687,0.83,0.622,-49.44054783,-16.75881189,893.6,360.0,842.0,147.26,NaN,NaN,8583.0,Urbano,6.2,27991.25,74750.32,36915.04,145857.6,20554.2,166.41,8053.0,20664.57,Demais serviços,28227691.0,284.0,5.0,1.0,56.0,0.0,2.0,29.0,110.0,26.0,4.0,5.0,0.0,2.0,10.0,12.0,4.0,6.0,6.0,1.0,5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2158.0,1246.0,0.0,NaN,NaN,NaN,1.0
1,Abadia Dos Dourados,MG,0,6704.0,6704.0,0.0,2328.0,1481.0,847.0,4154.0,38.0,207.0,260.0,351.0,2709.0,589.0,4479.0,18017.0,2207.0,0.69,0.693,0.839,0.563,-47.39683244,-18.48756496,753.12,77.0,296.0,881.06,Caminhos Do Cerrado,D,6972.0,Rural Adjacente,50524.57,25917.7,62689.23,28083.79,167215.28,12873.5,180.09,7037.0,25591.7,Demais serviços,17909274.0,476.0,6.0,6.0,30.0,1.0,2.0,34.0,190.0,70.0,28.0,11.0,0.0,4.0,15.0,29.0,2.0,9.0,14.0,6.0,19.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2227.0,1142.0,0.0,NaN,NaN,NaN,1.0
2,Abadiânia,GO,0,15757.0,15609.0,148.0,4655.0,3233.0,1422.0,10656.0,139.0,650.0,894.0,1087.0,6896.0,990.0,10307.0,33085.0,2202.0,0.69,0.671,0.841,0.579,-48.71881214,-16.18267186,1017.55,227.0,720.0,"1,045.13",Região Turística Do Ouro E Cristais,C,19614.0,Rural Adjacente,42.84,16728.3,138198.58,63396.2,261161.91,26822.58,287984.49,18427.0,15628.4,Demais serviços,37513019.0,288.0,5.0,9.0,26.0,0.0,2.0,7.0,117.0,12.0,57.0,2.0,1.0,0.0,7.0,15.0,3.0,11.0,5.0,1.0,8.0,0.0,0.0,1.0,34.0,1.0,1.0,1.0,1.0,33724584.0,67091904.0,2838.0,1426.0,0.0,NaN,NaN,NaN,3.0
3,Abaeté,MG,0,22690.0,22690.0,0.0,7694.0,6667.0,1027.0,18464.0,176.0,856.0,1233.0,1539.0,11979.0,2681.0,1862.0,7502.0,1994.0,0.698,0.72,0.848,0.556,-45.44619142,-19.15584769,644.74,1230.0,1716.0,"1,817.07",Lago De Três Marias,D,23223.0,Urbano,113824.6,31002.62,172.33,86081.41,403241.27,26994.09,430235.36,23574.0,18250.42,Demais serviços,NaN,621.0,18.0,1.0,40.0,0.0,1.0,20.0,303.0,62.0,30.0,9.0,6.0,4.0,28.0,27.0,2.0,15.0,19.0,9.0,27.0,0.0,0.0,NaN,NaN,2.0,2.0,2.0,2.0,44974716.0,371922572.0,6928.0,2953.0,0.0,NaN,NaN,NaN,4.0
4,Abaetetuba,PA,0,141100.0,141040.0,60.0,31061.0,19057.0,12004.0,82956.0,1354.0,5567.0,7618.0,8905.0,53516.0,5996.0,25200.0,700872.0,3530.0,0.628,0.579,0.798,0.537,-48.88440382,-1.723469863,10.12,3389.0,1218.0,"1,610.65",Araguaia-Tocantins,D,156292.0,Urbano,140463.72,58610,468128.69,486872.4,1154074.81,95180.48,1249255.29,151934.0,8222.36,"Administração, defesa, educação e saúde públic...",NaN,931.0,4.0,2.0,43.0,0.0,1.0,27.0,500.0,16.0,31.0,6.0,1.0,1.0,22.0,16.0,2.0,155.0,33.0,15.0,56.0,0.0,0.0,NaN,NaN,2.0,4.0,2.0,4.0,76181384.0,800078483.0,5277.0,25661.0,0.0,NaN,NaN,NaN,2.0

In [3]:
cidades.drop(['CITY', 'IDHM Ranking 2010', 'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'LONG', 'LAT', 'GVA_MAIN', 'REGIAO_TUR', 'MUN_EXPENDIT', 'HOTELS', 'BEDS', 'Pr_Agencies', 'Pu_Agencies', 'Pr_Bank', 'Pu_Bank', 'Pr_Assets', 'Pu_Assets','UBER','MAC','WAL-MART'], axis=1, inplace=True)

In [4]:
cidades.head()

,STATE,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,IBGE_1,IBGE_1-4,IBGE_5-9,IBGE_10-14,IBGE_15-59,IBGE_60+,IBGE_PLANTED_AREA,IBGE_CROP_PRODUCTION_$,IDHM,ALT,PAY_TV,FIXED_PHONES,AREA,CATEGORIA_TUR,ESTIMATED_POP,RURAL_URBAN,GVA_AGROPEC,GVA_INDUSTRY,GVA_SERVICES,GVA_PUBLIC,GVA_TOTAL,TAXES,GDP,POP_GDP,GDP_CAPITA,COMP_TOT,COMP_A,COMP_B,COMP_C,COMP_D,COMP_E,COMP_F,COMP_G,COMP_H,COMP_I,COMP_J,COMP_K,COMP_L,COMP_M,COMP_N,COMP_O,COMP_P,COMP_Q,COMP_R,COMP_S,COMP_T,COMP_U,Cars,Motorcycles,Wheeled_tractor,POST_OFFICES
0,GO,0,6876.0,6876.0,0.0,2137.0,1546.0,591.0,5300.0,69.0,318.0,438.0,517.0,3542.0,416.0,319.0,1843.0,0.708,893.6,360.0,842.0,147.26,NaN,8583.0,Urbano,6.2,27991.25,74750.32,36915.04,145857.6,20554.2,166.41,8053.0,20664.57,284.0,5.0,1.0,56.0,0.0,2.0,29.0,110.0,26.0,4.0,5.0,0.0,2.0,10.0,12.0,4.0,6.0,6.0,1.0,5.0,0.0,0.0,2158.0,1246.0,0.0,1.0
1,MG,0,6704.0,6704.0,0.0,2328.0,1481.0,847.0,4154.0,38.0,207.0,260.0,351.0,2709.0,589.0,4479.0,18017.0,0.69,753.12,77.0,296.0,881.06,D,6972.0,Rural Adjacente,50524.57,25917.7,62689.23,28083.79,167215.28,12873.5,180.09,7037.0,25591.7,476.0,6.0,6.0,30.0,1.0,2.0,34.0,190.0,70.0,28.0,11.0,0.0,4.0,15.0,29.0,2.0,9.0,14.0,6.0,19.0,0.0,0.0,2227.0,1142.0,0.0,1.0
2,GO,0,15757.0,15609.0,148.0,4655.0,3233.0,1422.0,10656.0,139.0,650.0,894.0,1087.0,6896.0,990.0,10307.0,33085.0,0.69,1017.55,227.0,720.0,"1,045.13",C,19614.0,Rural Adjacente,42.84,16728.3,138198.58,63396.2,261161.91,26822.58,287984.49,18427.0,15628.4,288.0,5.0,9.0,26.0,0.0,2.0,7.0,117.0,12.0,57.0,2.0,1.0,0.0,7.0,15.0,3.0,11.0,5.0,1.0,8.0,0.0,0.0,2838.0,1426.0,0.0,3.0
3,MG,0,22690.0,22690.0,0.0,7694.0,6667.0,1027.0,18464.0,176.0,856.0,1233.0,1539.0,11979.0,2681.0,1862.0,7502.0,0.698,644.74,1230.0,1716.0,"1,817.07",D,23223.0,Urbano,113824.6,31002.62,172.33,86081.41,403241.27,26994.09,430235.36,23574.0,18250.42,621.0,18.0,1.0,40.0,0.0,1.0,20.0,303.0,62.0,30.0,9.0,6.0,4.0,28.0,27.0,2.0,15.0,19.0,9.0,27.0,0.0,0.0,6928.0,2953.0,0.0,4.0
4,PA,0,141100.0,141040.0,60.0,31061.0,19057.0,12004.0,82956.0,1354.0,5567.0,7618.0,8905.0,53516.0,5996.0,25200.0,700872.0,0.628,10.12,3389.0,1218.0,"1,610.65",D,156292.0,Urbano,140463.72,58610,468128.69,486872.4,1154074.81,95180.48,1249255.29,151934.0,8222.36,931.0,4.0,2.0,43.0,0.0,1.0,27.0,500.0,16.0,31.0,6.0,1.0,1.0,22.0,16.0,2.0,155.0,33.0,15.0,56.0,0.0,0.0,5277.0,25661.0,0.0,2.0

In [5]:
state_encode = pd.get_dummies(cidades['STATE'])
rural_encode = pd.get_dummies(cidades['RURAL_URBAN'])
categoria_encode = pd.get_dummies(cidades['CATEGORIA_TUR'])
cidades.drop(['STATE', 'RURAL_URBAN', 'CATEGORIA_TUR'], axis = 1, inplace = True)

concatenado = pd.concat([cidades, state_encode, rural_encode, categoria_encode], axis = 1)

In [6]:
concatenado.head()

,CAPITAL,IBGE_RES_POP,IBGE_RES_POP_BRAS,IBGE_RES_POP_ESTR,IBGE_DU,IBGE_DU_URBAN,IBGE_DU_RURAL,IBGE_POP,IBGE_1,IBGE_1-4,IBGE_5-9,IBGE_10-14,IBGE_15-59,IBGE_60+,IBGE_PLANTED_AREA,IBGE_CROP_PRODUCTION_$,IDHM,ALT,PAY_TV,FIXED_PHONES,AREA,ESTIMATED_POP,GVA_AGROPEC,GVA_INDUSTRY,GVA_SERVICES,GVA_PUBLIC,GVA_TOTAL,TAXES,GDP,POP_GDP,GDP_CAPITA,COMP_TOT,COMP_A,COMP_B,COMP_C,COMP_D,COMP_E,COMP_F,COMP_G,COMP_H,...,Wheeled_tractor,POST_OFFICES,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,MG,MS,MT,PA,PB,PE,PI,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO,Intermediário Adjacente,Intermediário Remoto,Rural Adjacente,Rural Remoto,Sem classificação,Urbano,A,B,C,D,E
0,0,6876.0,6876.0,0.0,2137.0,1546.0,591.0,5300.0,69.0,318.0,438.0,517.0,3542.0,416.0,319.0,1843.0,0.708,893.6,360.0,842.0,147.26,8583.0,6.2,27991.25,74750.32,36915.04,145857.6,20554.2,166.41,8053.0,20664.57,284.0,5.0,1.0,56.0,0.0,2.0,29.0,110.0,26.0,...,0.0,1.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,0,6704.0,6704.0,0.0,2328.0,1481.0,847.0,4154.0,38.0,207.0,260.0,351.0,2709.0,589.0,4479.0,18017.0,0.69,753.12,77.0,296.0,881.06,6972.0,50524.57,25917.7,62689.23,28083.79,167215.28,12873.5,180.09,7037.0,25591.7,476.0,6.0,6.0,30.0,1.0,2.0,34.0,190.0,70.0,...,0.0,1.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
2,0,15757.0,15609.0,148.0,4655.0,3233.0,1422.0,10656.0,139.0,650.0,894.0,1087.0,6896.0,990.0,10307.0,33085.0,0.69,1017.55,227.0,720.0,"1,045.13",19614.0,42.84,16728.3,138198.58,63396.2,261161.91,26822.58,287984.49,18427.0,15628.4,288.0,5.0,9.0,26.0,0.0,2.0,7.0,117.0,12.0,...,0.0,3.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
3,0,22690.0,22690.0,0.0,7694.0,6667.0,1027.0,18464.0,176.0,856.0,1233.0,1539.0,11979.0,2681.0,1862.0,7502.0,0.698,644.74,1230.0,1716.0,"1,817.07",23223.0,113824.6,31002.62,172.33,86081.41,403241.27,26994.09,430235.36,23574.0,18250.42,621.0,18.0,1.0,40.0,0.0,1.0,20.0,303.0,62.0,...,0.0,4.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0,141100.0,141040.0,60.0,31061.0,19057.0,12004.0,82956.0,1354.0,5567.0,7618.0,8905.0,53516.0,5996.0,25200.0,700872.0,0.628,10.12,3389.0,1218.0,"1,610.65",156292.0,140463.72,58610,468128.69,486872.4,1154074.81,95180.48,1249255.29,151934.0,8222.36,931.0,4.0,2.0,43.0,0.0,1.0,27.0,500.0,16.0,...,0.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [7]:
novo = concatenado.dropna()

In [8]:
novo['AREA']= novo['AREA'].str.replace(',', '')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
x = novo.drop('IDHM', axis = 1)
y = novo['IDHM']

In [10]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

normalizador = MinMaxScaler(feature_range = (0,1))
x_norm = normalizador.fit_transform(x)

pca = PCA(n_components = 15)
x_pca = pca.fit_transform(x_norm)

In [11]:
print('Variância explicada dos componentes:', pca.explained_variance_ratio_)

Variância explicada dos componentes: [0.19583701 0.12162792 0.08095638 0.07072222 0.05173514 0.05057867
 0.0419547  0.03908119 0.03509221 0.03082314 0.02953088 0.02239071
 0.02062089 0.01971804 0.01785794]

In [12]:
sum(pca.explained_variance_ratio_)

0.8285270322569858

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

modelo = RandomForestRegressor(n_estimators = 100, n_jobs = -1)
kfold = KFold(n_splits = 3)
resultado = cross_val_score(modelo, x_pca, y, cv = kfold, n_jobs = -1)
print(resultado.mean())

0.8037492829178357

In [14]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

minimos_split = np.array([2,3,4])
maximo_nivel = np.array([3,5,7,9,11,14])
minimo_leaf = np.array([3,4,5,6])
valores_grid = {'min_samples_split': minimos_split, 'max_depth': maximo_nivel, 'min_samples_leaf': minimo_leaf}

modelo1 = RandomForestRegressor(n_estimators = 100, n_jobs = -1)

gridRandomForest = RandomizedSearchCV(estimator = modelo1, param_distributions = valores_grid, cv = 3, n_iter = 50, n_jobs = -1)
gridRandomForest.fit(x_pca,y)

print('Mínimo split: ', gridRandomForest.best_estimator_.min_samples_split)
print('Máxima profundidade: ', gridRandomForest.best_estimator_.max_depth)
print('Mínimo leaf: ', gridRandomForest.best_estimator_.min_samples_leaf)
print('R2: ', gridRandomForest.best_score_)

Mínimo split:  3
Máxima profundidade:  14
Mínimo leaf:  3
R2:  0.8074831918564617